scalableinternetservices/Foodies

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss

See https://github.com/twbs/bootstrap-sass
[Finishes #105945968]

Import bootstrap

---

app/controllers/recipes_controller.rb
app/views/recipes/_form.html.erb
app/views/recipes/show.html.erb
db/seeds.rb

Modify show recipe

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/colors.css
app/assets/stylesheets/style.scss
app/views/layouts/application.html.erb
config/routes.rb

- Changed root to recipes#index
- Imported css template
- Created basic application layout
[Finishes #105538050,#105898598]

Import style template and create basic application layout

---

app/views/recipes/_form.html.erb

User can edit recipe

---

app/assets/javascripts/profile.coffee
app/assets/stylesheets/profile.scss
app/controllers/profile_controller.rb
app/helpers/profile_helper.rb
app/views/profile/index.html.erb
config/routes.rb
test/controllers/profile_controller_test.rb
test/test_helper.rb

add a profile controller and profile index view

---

app/controllers/masterpieces_controller.rb
app/controllers/recipes_controller.rb
app/views/masterpieces/show.html.erb
app/views/recipes/show.html.erb
config/routes.rb

[Finishes #106528708,#106528678]

user can like a recipe or masterpiece

---

app/controllers/recipes_controller.rb
app/views/recipes/show.html.erb
config/routes.rb

user could save a recipe

---

Gemfile
Gemfile.lock
app/controllers/recipes_controller.rb
app/models/recipe.rb
app/models/step.rb
app/views/recipes/_form.html.erb
app/views/recipes/show.html.erb
config/initializers/simple_form.rb
config/initializers/simple_form_bootstrap.rb
config/locales/simple_form.en.yml
lib/templates/erb/scaffold/_form.html.erb

- A user could create a recipe
- A user could edit recipe including ingredients and steps
- UI change for edit and create recipe with simple_form
[Finishes #106819844,#106353408,#106819806]

Modified recipe edit/create/show page.

---

app/controllers/masterpieces_controller.rb
app/controllers/profile_controller.rb
app/controllers/recipes_controller.rb
app/views/masterpieces/_form.html.erb
app/views/masterpieces/index.html.erb
app/views/masterpieces/show.html.erb
app/views/recipes/show.html.erb
test/controllers/masterpieces_controller_test.rb

- User can upload masterpiece under one recipe

Create masterpiece under recipe

---

app/controllers/masterpieces_controller.rb
app/controllers/recipes_controller.rb
app/views/masterpieces/show.html.erb
app/views/recipes/show.html.erb
config/routes.rb

A user could unlike & unbookmark, button appearance changes accordingly

---

db/seeds.rb

- profile images
- recipe images
- masterpiece images
[Finish #107012982]

Add images to seed

---

.gitignore
config/environments/development.rb
db/seeds.rb

- change seed image url to be dropbox url
- change paperclip config to use local file system instead of s3 in development environment

Change seed image urls

---

app/views/layouts/application.html.erb
app/views/recipes/show.html.erb

- add recipe image
- add masterpice images
- rearrange layout
[Finish #106528664]

Nicer recipe show page

---

app/models/recipe.rb

Destroying recipe also destroys related masterpieces

Fix bug when destroying recipe

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/recipes_controller.rb
app/models/ingredient.rb
app/models/recipe.rb
app/views/recipes/_form.html.erb

[Finishes #107186664,#107186704]

Use nested_form to add/remove ingredients/steps

---

app/controllers/recipes_controller.rb
app/inputs/recipe_img_input.rb
app/inputs/step_img_input.rb
app/views/recipes/_form.html.erb
app/views/recipes/show.html.erb

- Modify step edit ui to look nicer
- User could see existing step/recipe image when editing recipe
[Finish #107206130, #107206388]

Nicer step edit ui and display existing image when editing

---

app/inputs/masterpiece_img_input.rb
app/views/masterpieces/_form.html.erb
app/views/masterpieces/show.html.erb

A user could see a nicer ui of masterpiece show page

---

app/assets/javascripts/collections.coffee
app/assets/stylesheets/collections.scss
app/controllers/collections_controller.rb
app/helpers/collections_helper.rb
app/models/collection.rb
app/models/collection_recipe.rb
app/models/recipe.rb
app/models/user.rb
app/models/user_save_collection.rb
app/views/collections/_form.html.erb
app/views/collections/edit.html.erb
app/views/collections/index.html.erb
app/views/collections/index.json.jbuilder
app/views/collections/new.html.erb
app/views/collections/show.html.erb
app/views/collections/show.json.jbuilder
config/routes.rb
db/migrate/20151104044029_create_collections.rb
db/migrate/20151104045048_create_user_save_collections.rb
db/migrate/20151104054110_create_collection_recipes.rb
db/schema.rb
test/controllers/collections_controller_test.rb
test/fixtures/collection_recipes.yml
test/fixtures/collections.yml
test/fixtures/user_save_collections.yml
test/models/collection_recipe_test.rb
test/models/collection_test.rb
test/models/user_save_collection_test.rb

Create collection model

---

Gemfile.lock
app/assets/javascripts/default.js
app/assets/javascripts/homepage.coffee
app/assets/javascripts/jquery.flexslider.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/flexslider.scss
app/assets/stylesheets/homepage.scss
app/assets/stylesheets/style.scss
app/controllers/homepage_controller.rb
app/controllers/recipes_controller.rb
app/helpers/homepage_helper.rb
app/models/recipe.rb
app/views/homepage/show.html.erb
config/routes.rb
db/migrate/20151012083526_create_recipes.rb
db/schema.rb
db/seeds.rb
test/controllers/homepage_controller_test.rb

Homepage Layout

---

db/seeds.rb

Add 10 more recipes to fill the homepage

Add more seed data

---

app/assets/javascripts/search.coffee
app/assets/stylesheets/search.scss
app/assets/stylesheets/style.scss
app/controllers/search_controller.rb
app/helpers/search_helper.rb
app/models/ingredient.rb
app/models/masterpiece.rb
app/models/recipe.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/search/_common.html.erb
app/views/search/find_by_ingredient.html.erb
app/views/search/find_by_masterpiece.html.erb
app/views/search/find_by_recipe.html.erb
app/views/search/find_by_user.html.erb
app/views/search/index.html.erb
config/routes.rb
test/controllers/search_controller_test.rb

1. add search controller to search by recipe, masterpiece, ingredient or user;
2. add search view to show title, image, like count etc;
3. ugly UI.
[Finishes #107091744,#107091560]

add search controller and search view

---

app/models/user.rb

- fix bug in find_for_database_authentication
- format code

Fix bug for user mode

---

app/controllers/search_controller.rb
app/views/search/find_by_ingredient.html.erb

- change search ingredient in controller
- change ui for displaying ingredient search result

Modify search ingredient

---

app/assets/stylesheets/style.scss

- tag (using btn-custom class) width is based on the content length
- add padding to btn-custom class

Change tag width to be based on the content

---

app/models/masterpiece.rb
app/models/recipe.rb
app/models/step.rb
app/models/user.rb
app/views/profile/index.html.erb
app/views/search/find_by_masterpiece.html.erb

- better masterpiece search result
- better profile tabs including recipe image and masterpiece image

Better search view and profile view

---

app/views/homepage/show.html.erb
app/views/masterpieces/show.html.erb
app/views/recipes/show.html.erb
app/views/search/find_by_masterpiece.html.erb
app/views/search/find_by_recipe.html.erb
app/views/search/find_by_user.html.erb

- recipe show view: add images of users liked it, users bookmarked it
- masterpiece show view: add images of users liked it
- display username instead of email in recipe-show, masterpiece-show and search-results

Better ui in recipe show, masterpiece show and search

---

config/environments/development.rb

- use rake assets:precompile to precompile
- assets won't be compiled when running in development

Don't compile assets in development
